"""
FragilityCalculator — Calculates architectural fragility scores for graph artefacts.

Requirements: 4.1–4.8, 7.1, 7.4, 7.5
"""

from __future__ import annotations

import asyncio
import logging
import os
from dataclasses import dataclass
from typing import Optional

import httpx

logger = logging.getLogger("insightgraph")

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434")
OLLAMA_COMPLEX_MODEL = os.getenv("OLLAMA_COMPLEX_MODEL", "qwen3-coder-next:q4_K_M")
OLLAMA_FALLBACK_MODEL = os.getenv("OLLAMA_FALLBACK_MODEL", "qwen2.5-coder:7b")

# Normalization constants
MAX_DEPENDENTS = 100
MAX_DEPTH = 20
MAX_COMPLEXITY = 50


@dataclass
class FragilityDetail:
    node_key: str
    name: str
    fragility_score: float              # 0–100
    previous_fragility_score: Optional[float]
    dependents_count: int
    graph_depth: int
    cyclomatic_complexity: int
    is_god_class: bool
    refactoring_recommendation: Optional[str]  # generated by Ollama if score > 80
    vulnerability_count: int = 0  # Requirements: 10.5


class FragilityCalculator:
    """
    Calculates Fragility_Score for each artefact in the dependency graph.

    Requirements: 4.1–4.8, 7.1, 7.4, 7.5
    """

    def __init__(self, neo4j_service, memory_nodes, memory_edges, semantic_analyzer):
        self._neo4j = neo4j_service
        # memory_nodes: dict {node_key: {"labels": [...], "properties": {...}}}
        # or list of dicts with "namespace_key" key — normalise to dict
        if isinstance(memory_nodes, dict):
            self._memory_nodes: dict = memory_nodes
        else:
            self._memory_nodes = {
                n.get("namespace_key", ""): n
                for n in (memory_nodes or [])
                if n.get("namespace_key")
            }
        self._memory_edges: list = memory_edges or []
        self._semantic_analyzer = semantic_analyzer
        self._cache: dict[str, FragilityDetail] = {}

    # ──────────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────────

    async def calculate(self, node_key: str) -> FragilityDetail:
        """
        Calculate FragilityDetail for a single node.

        Requirements: 4.1–4.3, 4.6, 4.7, 4.8, 7.1, 10.5
        """
        dependents_count = self._count_dependents(node_key)
        graph_depth = self._measure_depth(node_key)
        cyclomatic_complexity = self._get_complexity(node_key)
        vulnerabilities_count = self._count_vulnerabilities(node_key)

        score = self._compute_score(
            dependents_count, graph_depth, cyclomatic_complexity, vulnerabilities=vulnerabilities_count
        )
        is_god_class = dependents_count > 20  # task 1.4.7

        # Retrieve node name
        name = self._get_node_name(node_key)

        # Read previous score before persisting (task 1.4.5)
        previous_score = self._read_previous_score(node_key)

        # Persist to Neo4j (task 1.4.5)
        self._persist_score(node_key, score, previous_score)

        detail = FragilityDetail(
            node_key=node_key,
            name=name,
            fragility_score=score,
            previous_fragility_score=previous_score,
            dependents_count=dependents_count,
            graph_depth=graph_depth,
            cyclomatic_complexity=cyclomatic_complexity,
            is_god_class=is_god_class,
            refactoring_recommendation=None,
            vulnerability_count=vulnerabilities_count,
        )

        # Generate refactoring recommendation if score > 80 (task 1.4.6)
        if score > 80:
            detail.refactoring_recommendation = await self._generate_refactoring_recommendation(detail)

        self._cache[node_key] = detail
        return detail

    async def calculate_all(self) -> list[FragilityDetail]:
        """
        Calculate FragilityDetail for all nodes asynchronously.

        Requirements: 7.5
        """
        node_keys = self._get_all_node_keys()
        results = await asyncio.gather(
            *[self.calculate(key) for key in node_keys],
            return_exceptions=True,
        )
        details: list[FragilityDetail] = []
        for key, result in zip(node_keys, results):
            if isinstance(result, Exception):
                logger.warning("FragilityCalculator: error calculating %s: %s", key, result)
            else:
                details.append(result)
        return details

    def get_ranking(self, top_n: int = 20) -> list[FragilityDetail]:
        """
        Return top_n artefacts sorted by fragility_score descending, capped at 100.

        Requirements: 4.5
        """
        top_n = min(top_n, 100)
        sorted_details = sorted(
            self._cache.values(),
            key=lambda d: d.fragility_score,
            reverse=True,
        )
        return sorted_details[:top_n]

    # ──────────────────────────────────────────────
    # Score computation
    # ──────────────────────────────────────────────

    def _compute_score(
        self,
        dependents: int,
        depth: int,
        complexity: int,
        hops_to_frontend: int = 0,
        vulnerabilities: int = 0,
    ) -> float:
        """
        Weighted fragility formula clamped to [0, 100].

        score = min(100,
            (dependents_count / MAX_DEPENDENTS) * 40 +
            (graph_depth / MAX_DEPTH) * 30 +
            (cyclomatic_complexity / MAX_COMPLEXITY) * 30 +
            max(0, (hops_to_frontend - 3)) * 5 +
            min(vulnerabilities * 10, 30)
        )

        Requirements: 4.1, 4.2, 10.5
        """
        raw = (
            (dependents / MAX_DEPENDENTS) * 40
            + (depth / MAX_DEPTH) * 30
            + (complexity / MAX_COMPLEXITY) * 30
            + max(0, hops_to_frontend - 3) * 5
            + min(vulnerabilities * 10, 30)
        )
        return float(min(100.0, max(0.0, raw)))

    # ──────────────────────────────────────────────
    # Graph metric helpers
    # ──────────────────────────────────────────────

    def _count_dependents(self, node_key: str) -> int:
        """Count nodes that depend on (point to) this node."""
        if self._neo4j and getattr(self._neo4j, "is_connected", False):
            try:
                query = """
                MATCH (dependent)-[]->(target:Entity {namespace_key: $key})
                RETURN count(DISTINCT dependent) AS cnt
                """
                rows = self._neo4j.graph.run(query, key=node_key).data()
                if rows:
                    return int(rows[0].get("cnt", 0))
            except Exception as e:
                logger.warning("FragilityCalculator._count_dependents Neo4j error: %s", e)

        # Memory fallback — count edges pointing TO node_key
        count = 0
        for edge in self._memory_edges:
            tgt = edge.get("target") or edge.get("to")
            if tgt == node_key:
                count += 1
        return count

    def _measure_depth(self, node_key: str) -> int:
        """Measure the maximum depth of the dependency tree rooted at node_key."""
        if self._neo4j and getattr(self._neo4j, "is_connected", False):
            try:
                query = """
                MATCH path = (start:Entity {namespace_key: $key})-[*]->(leaf)
                RETURN max(length(path)) AS max_depth
                """
                rows = self._neo4j.graph.run(query, key=node_key).data()
                if rows and rows[0].get("max_depth") is not None:
                    return int(rows[0]["max_depth"])
                return 0
            except Exception as e:
                logger.warning("FragilityCalculator._measure_depth Neo4j error: %s", e)

        # Memory fallback — BFS to find max depth
        return self._bfs_max_depth(node_key)

    def _bfs_max_depth(self, start_key: str) -> int:
        """BFS over memory_edges to find max depth from start_key."""
        # Build adjacency: source → list of targets
        adj: dict[str, list[str]] = {}
        for edge in self._memory_edges:
            src = edge.get("source") or edge.get("from")
            tgt = edge.get("target") or edge.get("to")
            if src and tgt:
                adj.setdefault(src, []).append(tgt)

        from collections import deque
        visited: set[str] = {start_key}
        queue: deque[tuple[str, int]] = deque([(start_key, 0)])
        max_depth = 0

        while queue:
            current, depth = queue.popleft()
            max_depth = max(max_depth, depth)
            for neighbor in adj.get(current, []):
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append((neighbor, depth + 1))

        return max_depth

    def _get_complexity(self, node_key: str) -> int:
        """Get cyclomatic complexity from node properties."""
        if self._neo4j and getattr(self._neo4j, "is_connected", False):
            try:
                query = """
                MATCH (n:Entity {namespace_key: $key})
                RETURN n.cyclomatic_complexity AS complexity
                """
                rows = self._neo4j.graph.run(query, key=node_key).data()
                if rows and rows[0].get("complexity") is not None:
                    return int(rows[0]["complexity"])
                return 1
            except Exception as e:
                logger.warning("FragilityCalculator._get_complexity Neo4j error: %s", e)

        # Memory fallback
        node = self._memory_nodes.get(node_key, {})
        props = node.get("properties", node)  # support both formats
        complexity = props.get("cyclomatic_complexity", 1)
        return int(complexity) if complexity else 1

    def _count_vulnerabilities(self, node_key: str) -> int:
        """
        Count SecurityIssue nodes linked to this entity via HAS_VULNERABILITY relationship.
        
        Requirements: 10.5
        """
        if self._neo4j and getattr(self._neo4j, "is_connected", False):
            try:
                query = """
                MATCH (e:Entity {namespace_key: $key})-[:HAS_VULNERABILITY]->(s:SecurityIssue)
                RETURN count(s) AS vuln_count
                """
                rows = self._neo4j.graph.run(query, key=node_key).data()
                if rows and rows[0].get("vuln_count") is not None:
                    return int(rows[0]["vuln_count"])
                return 0
            except Exception as e:
                logger.warning("FragilityCalculator._count_vulnerabilities Neo4j error: %s", e)
        
        # Memory fallback - no vulnerability data in memory
        return 0

    def _get_node_name(self, node_key: str) -> str:
        """Retrieve the display name for a node."""
        if self._neo4j and getattr(self._neo4j, "is_connected", False):
            try:
                query = """
                MATCH (n:Entity {namespace_key: $key})
                RETURN n.name AS name
                """
                rows = self._neo4j.graph.run(query, key=node_key).data()
                if rows and rows[0].get("name"):
                    return str(rows[0]["name"])
            except Exception as e:
                logger.warning("FragilityCalculator._get_node_name Neo4j error: %s", e)

        node = self._memory_nodes.get(node_key, {})
        props = node.get("properties", node)
        name = props.get("name") or node_key.split(":")[-1]
        return str(name)

    def _get_all_node_keys(self) -> list[str]:
        """Get all node keys from Neo4j or memory."""
        if self._neo4j and getattr(self._neo4j, "is_connected", False):
            try:
                query = "MATCH (n:Entity) RETURN n.namespace_key AS key"
                rows = self._neo4j.graph.run(query).data()
                return [r["key"] for r in rows if r.get("key")]
            except Exception as e:
                logger.warning("FragilityCalculator._get_all_node_keys Neo4j error: %s", e)

        return list(self._memory_nodes.keys())

    # ──────────────────────────────────────────────
    # Neo4j persistence (task 1.4.5)
    # ──────────────────────────────────────────────

    def _read_previous_score(self, node_key: str) -> Optional[float]:
        """Read the current fragility_score before updating (becomes previous)."""
        if self._neo4j and getattr(self._neo4j, "is_connected", False):
            try:
                query = """
                MATCH (n:Entity {namespace_key: $key})
                RETURN n.fragility_score AS score
                """
                rows = self._neo4j.graph.run(query, key=node_key).data()
                if rows and rows[0].get("score") is not None:
                    return float(rows[0]["score"])
            except Exception as e:
                logger.warning("FragilityCalculator._read_previous_score Neo4j error: %s", e)

        # Check cache for previous value
        cached = self._cache.get(node_key)
        if cached is not None:
            return cached.fragility_score
        return None

    def _persist_score(
        self,
        node_key: str,
        score: float,
        previous_score: Optional[float],
    ) -> None:
        """
        Persist fragility_score and previous_fragility_score via MERGE.

        Requirements: 4.6, 7.1
        """
        if not (self._neo4j and getattr(self._neo4j, "is_connected", False)):
            return
        try:
            query = """
            MERGE (n:Entity {namespace_key: $key})
            SET n.fragility_score = $score,
                n.previous_fragility_score = $previous_score
            """
            self._neo4j.graph.run(
                query,
                key=node_key,
                score=score,
                previous_score=previous_score,
            )
        except Exception as e:
            logger.warning("FragilityCalculator._persist_score Neo4j error: %s", e)

    # ──────────────────────────────────────────────
    # Ollama refactoring recommendation (task 1.4.6)
    # ──────────────────────────────────────────────

    async def _generate_refactoring_recommendation(self, detail: FragilityDetail) -> str:
        """
        Generate a refactoring recommendation via Ollama when fragility_score > 80.

        Returns empty string if Ollama is unavailable or score <= 80.

        Requirements: 4.8
        """
        if detail.fragility_score <= 80:
            return ""

        prompt = (
            f"You are a senior software architect. The artefact '{detail.name}' "
            f"(key: {detail.node_key}) has a fragility score of {detail.fragility_score:.1f}/100.\n\n"
            f"Coupling profile:\n"
            f"- Dependents count: {detail.dependents_count}\n"
            f"- Graph depth: {detail.graph_depth}\n"
            f"- Cyclomatic complexity: {detail.cyclomatic_complexity}\n"
            f"- Is God Class: {detail.is_god_class}\n\n"
            "Provide a concise refactoring recommendation (2-4 sentences) to reduce this artefact's "
            "fragility. Focus on concrete architectural actions."
        )

        current_model = OLLAMA_COMPLEX_MODEL
        for attempt in range(2):
            try:
                async with httpx.AsyncClient(timeout=60.0) as client:
                    response = await client.post(
                        f"{OLLAMA_URL}/api/generate",
                        json={
                            "model": current_model,
                            "prompt": prompt,
                            "stream": False,
                            "options": {"temperature": 0.2, "num_predict": 300},
                        },
                    )
                    response.raise_for_status()
                    text = response.json().get("response", "").strip()
                    return text
            except httpx.ConnectError:
                logger.warning(
                    "FragilityCalculator: cannot connect to Ollama at %s", OLLAMA_URL
                )
                return ""
            except httpx.HTTPStatusError as e:
                if e.response.status_code == 500 and current_model != OLLAMA_FALLBACK_MODEL:
                    logger.warning(
                        "FragilityCalculator: model %s returned 500, switching to fallback %s",
                        current_model,
                        OLLAMA_FALLBACK_MODEL,
                    )
                    current_model = OLLAMA_FALLBACK_MODEL
                    continue
                logger.warning(
                    "FragilityCalculator: Ollama HTTP error on attempt %d: %s", attempt + 1, e
                )
                return ""
            except Exception as e:
                logger.warning(
                    "FragilityCalculator: Ollama error on attempt %d: %s", attempt + 1, e
                )
                return ""

        return ""
