"""
WeeklyDigest — Fase 4: Resumo semanal da arquitetura via LLM local.

Gerado automaticamente todo domingo (ou sob demanda via /api/digest/generate).

O digest responde:
  - O que mudou na arquitetura essa semana?
  - Quais são os top riscos do momento?
  - A arquitetura está degradando ou melhorando?
  - Hotspots novos que merecem atenção.
  - Recomendações de ação (não só análise).
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

import httpx

from ollama_runtime import OllamaRuntime, OllamaServiceError

logger = logging.getLogger("insightgraph.weekly_digest")


class WeeklyDigestGenerator:
    """
    Generates a weekly architecture digest by:
      1. Fetching the last N snapshots from the DB
      2. Computing metric trends (degrading, improving, stable)
      3. Collecting fired alerts from the week
      4. Asking the local LLM to synthesize a narrative in plain language
      5. Persisting the digest and returning it
    """

    def __init__(
        self,
        state_store,
        ollama_url: str = "http://localhost:11434",
        ollama_model: str = "qwen3.5:4b",
        ollama_runtime: OllamaRuntime | None = None,
    ):
        self._store = state_store
        self._ollama_url = ollama_url.rstrip("/")
        self._model = ollama_model
        self._runtime = ollama_runtime

    # ──────────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────────

    async def generate(self, weeks_back: int = 1) -> dict:
        """
        Generate the weekly digest for the last `weeks_back` weeks.

        Returns a dict with:
          - id, week_start, week_end
          - summary: structured metrics data
          - narrative: plain-language text generated by the LLM
          - generated_at
        """
        now = datetime.now(timezone.utc)
        week_end = now
        week_start = now - timedelta(weeks=weeks_back)

        week_start_str = week_start.strftime("%Y-%m-%d")
        week_end_str = week_end.strftime("%Y-%m-%d")

        logger.info("Generating weekly digest: %s → %s", week_start_str, week_end_str)

        # 1. Collect data
        snapshots = self._get_week_snapshots(week_start.timestamp(), week_end.timestamp())
        alerts = self._get_week_alerts(week_start.timestamp(), week_end.timestamp())

        # 2. Compute summary
        summary = self._compute_summary(snapshots, alerts)

        # 3. Generate LLM narrative
        narrative = await self._generate_narrative(summary, week_start_str, week_end_str)

        digest = {
            "id": str(uuid.uuid4()),
            "week_start": week_start_str,
            "week_end": week_end_str,
            "summary": summary,
            "narrative": narrative,
            "generated_at": time.time(),
        }

        try:
            self._store.save_weekly_digest(digest)
        except Exception as exc:
            logger.warning("Failed to persist digest: %s", exc)

        return digest

    def get_history(self, limit: int = 12) -> list[dict]:
        """Return recent weekly digests."""
        return self._store.list_weekly_digests(limit=limit)

    # ──────────────────────────────────────────────
    # Data collection
    # ──────────────────────────────────────────────

    def _get_week_snapshots(self, ts_start: float, ts_end: float) -> list[dict]:
        """Get all snapshots within the week window."""
        try:
            all_snaps = self._store.get_snapshots(page=1, limit=100)
            return [s for s in all_snaps if ts_start <= (s.get("timestamp") or 0) <= ts_end]
        except Exception as exc:
            logger.warning("Failed to fetch snapshots: %s", exc)
            return []

    def _get_week_alerts(self, ts_start: float, ts_end: float) -> list[dict]:
        """Get all fired alerts within the week window."""
        try:
            result = self._store.get_alert_history(page=1, limit=200)
            return [
                a for a in result.get("items", [])
                if ts_start <= (a.get("fired_at") or 0) <= ts_end
            ]
        except Exception as exc:
            logger.warning("Failed to fetch alerts: %s", exc)
            return []

    # ──────────────────────────────────────────────
    # Summary computation
    # ──────────────────────────────────────────────

    def _compute_summary(self, snapshots: list[dict], alerts: list[dict]) -> dict:
        if not snapshots:
            return {
                "no_data": True,
                "message": "No scans performed this week.",
                "scan_count": 0,
                "alert_count": len(alerts),
            }

        first = snapshots[-1]  # oldest
        last  = snapshots[0]   # newest

        def delta(metric: str) -> dict:
            v_before = float(first.get(metric) or 0)
            v_after  = float(last.get(metric) or 0)
            diff = v_after - v_before
            pct  = (diff / v_before * 100) if v_before else 0.0
            trend = "stable"
            if abs(pct) >= 5:
                trend = "degrading" if diff > 0 and metric in ("god_classes", "circular_deps", "dead_code", "total_edges") else "improving"
                if diff < 0 and metric in ("god_classes", "circular_deps", "dead_code"):
                    trend = "improving"
            return {"before": v_before, "after": v_after, "delta": diff, "delta_pct": round(pct, 1), "trend": trend}

        # Commits this week
        commits = list({s["commit_hash"] for s in snapshots if s.get("commit_hash")})
        authors = list({s["author"] for s in snapshots if s.get("author")})

        # Alert breakdown by severity
        alert_by_severity: dict[str, int] = {}
        for a in alerts:
            sev = a.get("severity", "info")
            alert_by_severity[sev] = alert_by_severity.get(sev, 0) + 1

        # Top alerts (critical + high)
        top_alerts = [
            {"message": a["message"], "severity": a["severity"], "metric": a.get("metric"), "commit": a.get("commit_hash", "")[:8]}
            for a in alerts
            if a.get("severity") in ("critical", "high")
        ][:10]

        return {
            "scan_count": len(snapshots),
            "commit_count": len(commits),
            "active_authors": authors,
            "alert_count": len(alerts),
            "alert_by_severity": alert_by_severity,
            "top_alerts": top_alerts,
            "metrics": {
                "total_nodes": delta("total_nodes"),
                "total_edges": delta("total_edges"),
                "god_classes": delta("god_classes"),
                "circular_deps": delta("circular_deps"),
                "dead_code": delta("dead_code"),
                "call_resolution_rate": delta("call_resolution_rate"),
            },
            "first_snapshot": {"timestamp": first.get("timestamp"), "commit": first.get("commit_hash"), "branch": first.get("branch")},
            "last_snapshot": {"timestamp": last.get("timestamp"), "commit": last.get("commit_hash"), "branch": last.get("branch")},
        }

    # ──────────────────────────────────────────────
    # LLM narrative
    # ──────────────────────────────────────────────

    async def _generate_narrative(self, summary: dict, week_start: str, week_end: str) -> str:
        """Ask the local LLM to write a human-readable architecture digest."""
        if summary.get("no_data"):
            return "No architectural activity detected this week. No scans were performed."

        metrics = summary.get("metrics", {})
        alerts  = summary.get("top_alerts", [])

        def fmt_metric(name: str, m: dict) -> str:
            trend_icon = {"degrading": "⬇️ worse", "improving": "⬆️ better", "stable": "➡️ stable"}.get(m.get("trend", "stable"), "")
            return f"  - {name}: {m.get('before', 0):.0f} → {m.get('after', 0):.0f} ({m.get('delta_pct', 0):+.1f}%) {trend_icon}"

        metrics_text = "\n".join([
            fmt_metric("Total nodes", metrics.get("total_nodes", {})),
            fmt_metric("Total edges (coupling)", metrics.get("total_edges", {})),
            fmt_metric("God classes", metrics.get("god_classes", {})),
            fmt_metric("Circular dependencies", metrics.get("circular_deps", {})),
            fmt_metric("Dead code", metrics.get("dead_code", {})),
            fmt_metric("Call resolution rate", metrics.get("call_resolution_rate", {})),
        ])

        alerts_text = "\n".join(
            f"  - [{a['severity'].upper()}] {a['message']}" for a in alerts
        ) if alerts else "  - None"

        prompt = f"""You are an expert software architect reviewing the weekly health of a codebase.

Week: {week_start} to {week_end}
Scans performed: {summary.get('scan_count', 0)}
Commits analyzed: {summary.get('commit_count', 0)}
Active authors: {', '.join(summary.get('active_authors', [])) or 'unknown'}

METRIC CHANGES THIS WEEK:
{metrics_text}

TOP ALERTS FIRED:
{alerts_text}

Write a concise weekly architecture digest (3-5 paragraphs) in plain language covering:
1. Overall architectural health (improving, degrading, or stable?)
2. Key risks that need attention
3. What changed most significantly
4. Specific recommendations for the team (actionable, not vague)

Be direct and opinionated. Don't just describe — recommend. Use bullet points for recommendations.
Do not use markdown headers. Write as if briefing a tech lead."""

        try:
            if self._runtime is not None:
                data = await self._runtime.generate(
                    model=self._model,
                    prompt=prompt,
                    timeout=90.0,
                    retries=1,
                    options={"temperature": 0.3, "num_predict": 600},
                    keep_alive="10m",
                )
                return str(data.get("response") or "").strip()
            async with httpx.AsyncClient(timeout=90.0) as client:
                resp = await client.post(
                    f"{self._ollama_url}/api/generate",
                    json={
                        "model": self._model,
                        "prompt": prompt,
                        "stream": False,
                        "options": {"temperature": 0.3, "num_predict": 600},
                    },
                )
                resp.raise_for_status()
                data = resp.json()
                return data.get("response", "").strip()
        except OllamaServiceError as exc:
            logger.warning("LLM narrative generation failed: %s", exc)
            return self._fallback_narrative(summary)
        except Exception as exc:
            logger.warning("LLM narrative generation failed: %s", exc)
            return self._fallback_narrative(summary)

    def _fallback_narrative(self, summary: dict) -> str:
        """Plain-text fallback when LLM is unavailable."""
        metrics = summary.get("metrics", {})
        lines = [f"Weekly digest — {summary.get('scan_count', 0)} scan(s), {summary.get('commit_count', 0)} commit(s).\n"]

        degrading = [k for k, v in metrics.items() if v.get("trend") == "degrading"]
        improving = [k for k, v in metrics.items() if v.get("trend") == "improving"]

        if degrading:
            lines.append(f"Degrading metrics: {', '.join(degrading)}.")
        if improving:
            lines.append(f"Improving metrics: {', '.join(improving)}.")

        alert_count = summary.get("alert_count", 0)
        if alert_count:
            critical = summary.get("alert_by_severity", {}).get("critical", 0)
            lines.append(f"{alert_count} alert(s) fired this week ({critical} critical).")
        else:
            lines.append("No alerts fired this week.")

        return " ".join(lines)
